name: Base

on:
  workflow_call:

jobs:
  systems:
    name: System
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["systems"]'
      cargo_profiles: ${{vars.CARGO_PROFILES}}
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: ${{vars.RUST_TOOLCHAINS}}
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  buildsys:
    name: Builder
    uses: ./.github/workflows/bake.yml
    needs: [systems]
    with:
      bake_targets: '["buildsys"]'
      cargo_profiles: ${{vars.CARGO_PROFILES}}
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: ${{vars.RUST_TOOLCHAINS}}
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  complement:
    name: Tester
    uses: ./.github/workflows/bake.yml
    needs: [systems]
    with:
      bake_targets: '["complement-tester"]'
      cargo_profiles: ${{vars.CARGO_PROFILES}}
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: ${{vars.RUST_TOOLCHAINS}}
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}
