name: Build

on:
  workflow_call:

jobs:
  install:
    name: Install
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["install"]'
      cargo_profiles: ${{vars.CARGO_PROFILES}}
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: ${{vars.RUST_TOOLCHAINS}}
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  complement:
    name: Complement Testee
    uses: ./.github/workflows/bake.yml
    needs: [install]
    with:
      bake_targets: '["complement-testee"]'
      cargo_profiles: ${{vars.CARGO_PROFILES}}
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: ${{vars.RUST_TOOLCHAINS}}
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}
