name: Linting

on:
  workflow_call:

jobs:
  fmt:
    name: Format
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["fmt"]'
      cargo_profiles: '["test"]'
      feat_sets: '["none"]'
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: '["nightly"]'
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  audit:
    name: Audit
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["audit"]'
      cargo_profiles: '["test"]'
      feat_sets: '["none"]'
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: '["nightly"]'
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  lychee:
    name: Lychee
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["lychee"]'
      cargo_profiles: '["test"]'
      feat_sets: '["none"]'
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: '["nightly"]'
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  clippy:
    name: Clippy
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["clippy"]'
      cargo_profiles: ${{vars.CARGO_PROFILES}}
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: ${{vars.RUST_TOOLCHAINS}}
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}

  doc:
    name: Docs
    needs: [clippy]
    uses: ./.github/workflows/bake.yml
    with:
      bake_targets: '["docs"]'
      cargo_profiles: '["test"]'
      feat_sets: ${{vars.FEAT_SETS}}
      machines: ${{vars.MACHINES}}
      rust_targets: ${{vars.RUST_TARGETS}}
      rust_toolchains: '["nightly"]'
      sys_names: ${{vars.SYS_NAMES}}
      sys_targets: ${{vars.SYS_TARGETS}}
      sys_versions: ${{vars.SYS_VERSIONS}}
