name: Main

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  inputs: ${{github.event.inputs}}

jobs:
  base:
    name: Base
    uses: ./.github/workflows/base.yml

  deps:
    name: Deps
    uses: ./.github/workflows/deps.yml
    needs: [base]

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    needs: [deps]

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [deps]

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    needs: [build]
